import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'

type name = {
  name: string
}

export default function Home({ name }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <div className="mx-auto container">
          <h1 className="text-4xl text-center py-24">Hello, {name}!</h1>
        </div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps<name> = async () => {
  const res = await fetch('http://localhost:3000/api/hello')
  const { name } = await res.json()
  return {
    props: {
      name,
    },
  }
}
